theme: jekyll-theme-cayman

title: Mon Wiki
description: Here be my notes 😉

show_downloads: no
google_analytics: UA-107201783-1

github:
  repository_url: /wiki
  # owner_url: https://natsec.fr
  owner_url: repository_url
